import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import Nav from "../components/Nav";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <h1 className="text-3xl font-bold underline">
            This is tailwind-ed text
          </h1>
          <div>This is about page</div>
        </main>
      </Layout>
    </div>
  );
};

export default Home;
